### PR TITLE
sbt web 1.0 

### PR DESCRIPTION
**Pull request by benoit-ponsero**
thanks to mkurz,

His sbt web 1.0 update is functionnal. I've test it on a 2.6 play project. 

Can you merge and publish ?

### CODE REVIEW

**Comment by jroper** [comment]
Hi @noisycr1cket, will this ever be merged/released, or should we fork sbt-concat?

**Comment by jroper** [comment]
And just to make clear, it's completely ok if you don't want to maintain this anymore (I notice nothing has been done for almost 3 years), so I'm guessing you don't want to maintain it anymore, I just wanted to ask before forking it.

**Comment by noisycr1cket** [comment]
Sorry everyone, this project has definitely fallen by the wayside. If anyone wants to take over maintaining it, I'm definitely open to it!

**Comment by jroper** [comment]
I'm happy to pull it into the sbt GitHub organisation as long as you're happy with that. I'm not saying that I'll necessarily maintain it, but if it's in that org there are a large number of people that are active enough that it will get some maintenance, at least people reviewing/merging PRs and cutting releases.

**Comment by jroper** [comment]
@noisycr1cket If you transfer the repo to me, I can then transfer it into the sbt organization (GitHub won't let you transfer repos into organizations that you don't have create repo permission on, that's why it has to go through me).

**Comment by mkurz** [comment]
@noisycr1cket @jroper Can we also please transfer https://github.com/noisycr1cket/sbt-css-compress to the sbt GitHub organisation?
Thanks!

**Comment by mkurz** [comment]
And maybe even https://github.com/noisycr1cket/sbt-closure (but I didn't use the repo myself)

**Comment by noisycr1cket** [comment]
I'm happy to transfer all of those over to @jroper

**Comment by noisycr1cket** [comment]
@jroper are you fine with @mkurz request? I've already started the transfer process for this repo.

**Comment by jroper** [comment]
I've accepted the transfer add will get to transfering to SBT org tomorrow. I'll have a look at the other repos, just want to make sure they won't be duplicated things already in the SBT org.

**Pull request merged**
